package group57.ssf.Rabib_2221005;

import group57.ssf.UserClasses.User;

public class Administrator extends User {
    private int officeId;
    private String department;
    private String adminAccessLevel;

    public Administrator(int id, String password, String fullName, String email, String contact, String bloodType, String gender, String role, String status, float salary, int officeId, String department, String adminAccessLevel) {
        super(id, password, fullName, email, contact, bloodType, gender, role, status, salary);
        this.officeId = officeId;
        this.department = department;
        this.adminAccessLevel = adminAccessLevel;
    }

    // Getters & Setters
    public int getOfficeId() { return officeId; }
    public void setOfficeId(int officeId) { this.officeId = officeId; }

    public String getDepartment() { return department; }
    public void setDepartment(String department) { this.department = department; }

    public String getAdminAccessLevel() { return adminAccessLevel; }
    public void setAdminAccessLevel(String adminAccessLevel) { this.adminAccessLevel = adminAccessLevel; }

    // Admin-specific methods
    public void AddNewUser() {
        System.out.println("New user added by admin.");
    }

    public void CreateNewTeam() {
        System.out.println("Team created by admin.");
    }

    public void SendNotification() {
        System.out.println("Notification sent by admin.");
    }

    public void ViewInventory() {
        System.out.println("Inventory viewed by admin.");
    }

    public void SearchUserInfo() {
        System.out.println("User info searched by admin.");
    }

    public void GenerateReport() {
        System.out.println("Report generated by admin.");
    }
}